WHITESPACE = _{ " " | "\t" | "\n" | "\r\n" }

single_line_comment = @{ "%" ~ (!NEWLINE ~ ANY)* }
COMMENT = _{ single_line_comment }

text = { (!"}" ~ ANY)* }

title = { "\\title{" ~ text ~ "}" }

math = { "#{" ~ text ~ "}" }
p = { "\\p{" ~ text ~ "}" }
ol = { "\\ol{" ~ text ~ "}" }
ul = { "\\ul{" ~ text ~ "}" }
li = { "\\li{" ~ text ~ "}" }

top = {
  title
  | p
  | ol | ul | li
}
file = { SOI ~ top* ~ EOI }
