WHITESPACE = _{ " " | "\t" | "\n" | "\r\n" }

single_line_comment = @{ "%" ~ (!NEWLINE ~ ANY)* }
COMMENT = _{ single_line_comment }

title = { "\\title{" ~ (!"}" ~ ANY)* ~ "}" }
p = { "\\p{" ~ (!"}" ~ ANY)* ~ "}" }
ol = { "\\ol{" ~ (!"}" ~ ANY)* ~ "}" }
ul = { "\\ul{" ~ (!"}" ~ ANY)* ~ "}" }
li = { "\\li{" ~ (!"}" ~ ANY)* ~ "}" }
top = {
  title
  | p
  | ol | ul | li
}
file = { SOI ~ top* ~ EOI }
